version: '2'

services:
  workers:
    build:
      context: .
      dockerfile: ./etc/dev/node/Dockerfile
    volumes:
      - $PWD:/app
    command: "yarn start-workers"
    environment:
      - "MESSAGE_BROKER=amqp://guest:guest@rmq:5672"
      - "ELASTIC_HOST=elasticsearch:9200"
      - "ELASTIC_LOGS=error"

  api:
    extends:
      service: workers
      file: docker-compose.yml
    command: "yarn start"
    ports:
      - "3000:3000"

  rmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - "5601:5601"
    volumes:
      - "./etc/dev/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"